Kong/go-apiops

- convertoas3/oas3.go
- convertoas3/oas3_testfiles/12-path-parameter-regex.expected.json
- convertoas3/oas3_testfiles/12-path-parameter-regex.yaml
for each operation in the path, the path would be escaped again.
> fix(oas): escape path only once

- cmd/openapi2kong.go
- cmd/root.go
state is not an accurate description of incoming OAS files for the openapi2kong command.  Updated that to spec but kept the short argument the same.
Tidy up the general CLI usage text about kced and the librarys purpose
> fix(cli) updates arg for openapi2kong and general CLI message

- cmd/openapi2kong.go
original commit: https://github.com/Kong/go-apiops/commit/1ab34b0874470a9bbde25086993303c499fb59df
> fix(oas2kong): revert accidental arg rename

- cmd/merge.go
- cmd/openapi2kong.go
- cmd/patch.go
- cmd/version.go
- convertoas3/oas3.go
- deckformat/deckformat.go
- deckformat/deckformat_test.go
- jsonbasics/jsonbasics.go
- jsonbasics/jsonbasics_test.go
- merge/merge.go
- merge/merge_test.go
This records actions taken in the `_ignore` array of the file. This key is being ignored in the decK file format, hence safe to use.
It's not obvious however and potentially can get mixed with other items added by users in that array. Hence the preference is to move the history array to a new top-level field `_history`, but that would require changes to Kong and decK to ensure they ignore the field.
Todo:
> feat(track): add info to track build history of file

- deckformat/deckformat.go
- deckformat/deckformat_test.go
deck doesn't support the `_ignore` and `_comment` fields
> chore(history): temporary disable history recording

- cmd/patch.go
> fix(patch): typo in --help example

- cmd/version.go
- deckformat/deckformat.go
- deckformat/deckformat_test.go
In GitOps we do not want to show this info since it might trigger unnecessary changes in the resulting files.
fixes #37
> fix(history): do not show version nor commit

- convertoas3/oas3.go
depending on the name the plugin was inserted at the wrong array index. Causing duplicates, or missing plugins.
> fix(oas): properly order plugins added to routes

- jsonbasics/jsonbasics.go
- jsonbasics/jsonbasics_test.go
The array must be set as `[]interface{}` to be recognized in the next `GetObjectArryField` call.
> feat(jsonbasics): function to set an array of objects

- cmd/merge.go
- cmd/openapi2kong.go
- cmd/patch.go
- cmd/root.go
- deckformat/dbless_test.go
- filebasics/filebasics.go
- merge/merge_test.go
- patch/patch_test.go
reduces duplicate code and has the same constant values as deck. also makes the CLI argument case insensitive
> fix(filebasics): implement constants for formats

- cmd/addtags.go
- cmd/listtags.go
- cmd/removetags.go
- deckformat/entitylocations.go
- tags/tags.go
- tags/tags_suite_test.go
- tags/tags_test.go
The tags package allows to;
- add tags
- remove tags
- remove unknown tags
- list tags
and has the accompanying CLI commands
> feat(tags): implement tags package

- cmd/addplugins.go
- cmd/removetags.go
- deckformat/deckformat.go
- deckformat/entitypointers.go
- jsonbasics/jsonbasics.go
- plugins/plugins.go
- plugins/plugins_suite_test.go
- plugins/plugins_test.go
- tags/tags.go
- tags/tags_test.go
- yamlbasics/yamlbasics.go
- yamlbasics/yamlbasics_suite_test.go
- yamlbasics/yamlbasics_test.go
The config file has not yet been implemented
JIRA ticket: APIOPS-40
> feat(cli): add 'add-plugins' command

- plugins/plugins.go
- plugins/plugins_test.go
also adds foreign-key support for consumer_groups (forthcoming in Kong 3.4, earlier version of consumer groups are not supported))
> fix(plugins): adding plugins with foreign keys

- go.mod
- go.sum
- openapi2kong/openapi2kong.go
- openapi2kong/service.go
- openapi2kong/validator.go
Hello,
This pull request aims to solve the issue raised here: https://github.com/Kong/go-apiops/issues/82
It replaces the current UUID generation library because of a known CVE. Luckily nothing functionally changes when replacing this with the Google's UUID library. The UUID versions remain the same, meaning version 4 remains version 4 and version 5 remains version 5. Tough, the actual function name is different in Google's library:
* `NewV4` --> `NewRandom`
* `NewV5` --> `NewSHA1`
The current testcases seem to cover the changes, except when generating random UUIDs (`docBaseName` in `openapi2kong.go` on line 480), which also happens to not be covered by tests at this moment. If this is required, let me know. Though I'd also wonder how to test this if the UUIDs are randomly generated. …
> fix(oas): use google's UUID generator for UUID generation

- deckformat/entitypointers.go
The format used here is deck specific. It is a table that handles many-to-many relationships; consumers <-> groups. Hence the group name is wrapped in an object to be able to assign tags.
> fix(tags): the entitylist for tags was missing acl-groups

- cmd/patch.go
- patch/patch_test.go
- patch/patchcli.go
the `--value` flag only supported object fields, for arrays using a patch file was required. This change now supports a `--value "[1,2,3]"` format for arrays.
> feat(patch): add arrays to CLI options

- openapi2kong/oas3_testfiles/04a-servers-upstream.expected.json
- openapi2kong/oas3_testfiles/04a-servers-upstream.yaml
- openapi2kong/service.go
https://github.com/Kong/go-apiops/issues/104
This change increases bit size in `strconv.ParseInt` from 16 to 64 to allow higher port numbers. Also previously when the input was unparseable, the error was ignored. Now we can return an error instead of silently setting a potentially incorrect port number.
> [openapi2kong] Fix server port parsing

- cmd/openapi2kong.go
- docs/learnservice_oas.yaml
- docs/security-o2k.md
- openapi2kong/oas3_testfiles/16-security-oidc-generation.expected.json
- openapi2kong/oas3_testfiles/16-security-oidc-generation.yaml
- openapi2kong/openapi2kong.go
- openapi2kong/openapi2kong_test.go
> feat(o2k): add OIDC Security conversions

- filebasics/filebasics.go
- go.mod
- go.sum
to prevent users from thinking the cli 'hangs'
> chore(filebasics): inform user if reading from stdin

- openapi2kong/oas3_testfiles/16-security-oidc-generation.expected.json
- openapi2kong/openapi2kong.go
since oidc is typically authorized at operation level, it was generated per route. But for cases where there is only 1 it would generate many similar configs per path.
Now it creates 1 on the service, and ONLY deviating ones per route
> fix(o2k): create leaner config by using service level oidc

- yamlbasics/selectors.go
often selectors can be specified multiple times. This object allows to deal with them easier by executing, collecting and deduplicating all of them.
> feat(selectors): add multi-selector object

- docs/learnservice_oas.yaml
- jsonbasics/jsonbasics.go
- logbasics/logbasics.go
- openapi2kong/oas3_testfiles/08-route-defaults-overrides.expected.json
- openapi2kong/oas3_testfiles/08-route-defaults-overrides.yaml
- openapi2kong/oas3_testfiles/11-references.expected.json
- openapi2kong/openapi2kong.go
This default should be left untouched unless you know what you are doing (same as strip_path). But the value will be honored now if given. The default is assumed to be the plain-path value. A parameterized path should have a lower precedence, hence if the value is given a parameterized path will get the priority-1.
> fix(o2k): use regex_priority in defaults if given

- cmd/namespace.go
- go.mod
- go.sum
- namespace/namespace.go
- namespace/namespace_suite_test.go
- namespace/namespace_test.go
replaces #32 
This one does not rely on gateway features to be added, but uses a pre-functions plugin to strip the added namespace again before proxying. Ugly but works.
Once a proper solution in gateway is in place, we can switch to that (instead of adding the plugin here).
The plugin config generated: https://github.com/Kong/go-apiops/pull/129/files#diff-77a71302fdcf78eb63e7b91cb21a5c04a1eee45dd70789265057526444df380fR248-R263
```
$ go-apiops namespace --help
Namespaces API paths by prefixing it.
By prefixing paths with a specific segment, colliding paths to services can be
namespaced to prevent the collisions. Eg. 2 API definitions that both expose a
'/list' path. By prefixing one with '/addressbook' and the other with '/cookbook'
the resulting paths '/addressbook/list' and …
```
> feat(namespace): add namespacing paths

- openapi2kong/openapi2kong.go
- openapi2kong/openapi2kong_test.go
PCRE engines have a limit of 32 characters.
the path-parameter-names need to be predictable, because they might reuse them in other places (request-transformer template for example). So truncation or truncation and replacing the last x-chars with a hash for uniqueness, will not work, since the names become unpredictable.
Then I think the only alternative is to throw an error in OAS2kong, and have the user preprocess them to shorter names, such that they are well informed about the new names in use. More work, but no surprises.
> fix(o2k): limit path-param names to 32 chars

- cmd/namespace.go
- namespace/namespace_host.go
- namespace/namespace_host_test.go
- namespace/namespace_test.go
This PR implements the second part of namespacing; hostname based.
See https://github.com/Kong/go-apiops/pull/129#issuecomment-1898698871 for an explanation of path-based and host-based namespacing.
> feat(namespace): add the host based namespace

- openapi2kong/oas3_testfiles/13-request-validator-plugin.expected.json
- openapi2kong/oas3_testfiles/13-request-validator-plugin.yaml
- openapi2kong/validator.go
https://github.com/Kong/go-apiops/issues/174
> fix(o2k): request-validator support +json suffix for schemas

- openapi2kong/oas3_testfiles/13-request-validator-plugin.expected.json
- openapi2kong/validator.go
"explode" defaulted to false.
When the style is "form" the "explode" default is now true, in all
other cases false.
OAS ref: https://swagger.io/specification/v3/#parameter-object (2nd table in this paragraph)
FTI-6088
> fix(o2k): param-explode default true if form style

- openapi2kong/validator.go
With recent deck changes that attemp to skip
filling defaults before sending to CP, the cmd
deck file openapi2kong had issues with the required field coming up as null, if it was not filled by
the user. With this change, we fill it with
false by default.
Fixes: https://github.com/Kong/go-apiops/issues/203
> fix: parameter.required field coming as nil

- openapi2kong/oas3_testfiles/17-request-validator-plugin-oneOf-usage.expected.json
- openapi2kong/oas3_testfiles/17-request-validator-plugin-oneOf-usage.yaml
- openapi2kong/validator.go
This is related to FTI: https://konghq.atlassian.net/browse/FTI-6357
For: https://github.com/Kong/go-apiops/issues/230
> fix: fixed mixed-types array generation for req-validator plugin

- openapi2kong/oas3_testfiles/14-no-request-validator-plugin.yaml
- openapi2kong/validator.go
In the above case, we wish to skip the config
generation. Due to improper checking of the
generated parameter schema, it was not
getting assigned nil, as it is supposed to.
This change corrects the check to length
based-checking and improved the test to
validate the same.
For: https://github.com/Kong/go-apiops/issues/241
> fix: fixed req-validator config generation when both body and param schema are empty.

- merge/merge.go
- merge/merge_test.go
- merge/merge_testfiles/badenvvar.yml
- merge/merge_testfiles/file4.yml
- merge/merge_testfiles/file5.yml
- merge/merge_testfiles/file6.yml
- merge/merge_testfiles/file7.yml
- merge/merge_testfiles/test3_expected.json
- merge/merge_testfiles/test4_expected.json
For https://github.com/Kong/deck/issues/1575
Linked FTI: https://konghq.atlassian.net/browse/FTI-6578
Deck supports [env variables](https://docs.konghq.com/deck/gateway/sensitive-data/#using-deck-environment-variables).
I checked and the following yaml file is accepted by deck sync:
```
_format_version: "${{ env "DECK_FORMAT_VERSION" }}"
services:
- connect_timeout: 60000
id: 58076db2-28b6-423b-ba39-a797193017f7
host: mockbin.org
name: svc1
port: 80
protocol: http
read_timeout: 60000
retries: 5
```
_Note: Remember the outer quotes ““ to ensure you are passing a string value to _format_version_
_Deck internally parses it as a string but yaml can parse it as int._
As of now, deck file merge command is not accepting environment variable in the format version string 
but other commands (sync, …
> feat: using env vars for format_version string in deck files

- openapi2kong/oas3_testfiles/20-empty-paths.expected.json
- openapi2kong/oas3_testfiles/20-empty-paths.yaml
- openapi2kong/oas3_testfiles/invalid/no-paths.yaml
- openapi2kong/openapi2kong.go
- openapi2kong/openapi2kong_test.go
in OpenAPI spec (OAS) YAML doc. Allow empty `.paths`.
Currently an OAS doc like this
```yaml
---
openapi: 3.0.0
info:
description: Hendrix AI Gateway
version: 1.0.0
title: Hendrix AI Gateway
servers:
- url: https://api.openai.com
```
results in a panic.
```bash
$ deck file openapi2kong --spec oas.yaml
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1010e5944]
goroutine 1 [running]:
github.com/kong/go-apiops/openapi2kong.Convert({0x14000572000, 0x4ea, 0x4eb}, {{0x0, 0x0, 0x0}, {0x0, 0x0}, {0x6b, 0xa7, ...}, ...})
github.com/kong/go-apiops@v0.1.41/openapi2kong/openapi2kong.go:717 +0xfe4
github.com/kong/deck/cmd.executeOpenapi2Kong(0x140001a4d00?, {0x14000238fc0?, 0x4?, 0x1011631d0?}) …
```
> fix openapi2kong: fail with error if no `.paths`

- openapi2kong/oas3_testfiles/21-nullable-path-param.expected.json
- openapi2kong/oas3_testfiles/21-nullable-path-param.yaml
- openapi2kong/openapi2kong.go
In this PR, we are introducing conditional step for allowing empty string as path param.
We have reports from customers where the regex `[^#?/]+` for parameters leads routing to 404 when a parameter is empty string, so when a parameter has `minLength` set to 0, we will use `[^#?/]*` instead.
Path parameters are mandatory in OpenAPI spec, and cannot be empty - however, when customers have [OData](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/) style apis, empty string could be valid.
Fixes https://github.com/Kong/go-apiops/issues/269, https://konghq.atlassian.net/browse/FTI-6687
Discussion for using minLength - https://konghq.atlassian.net/browse/FTI-6687?focusedCommentId=165300
> Fix: use nullable to allow empty path param

- cmd/openapi2kong.go
- openapi2kong/oas3_testfiles/20-ignore-circular-references.circular-yaml
- openapi2kong/oas3_testfiles/20-ignore-circular-references.expected_no_circular.json
- openapi2kong/oas3_testfiles/20-ignore-circular-references.generated_no_circular.json
- openapi2kong/openapi2kong.go
- openapi2kong/openapi2kong_test.go
Added new flag to ignore circular references in `openapi2kong` subcommand.
In some cases, circular references may actually be valid use cases for a particular specification design.
See https://pb33f.io/libopenapi/circular-references/ for more details.
> feat: add support for ignoring circular refs in OpenAPI spec
